#!/usr/bin/env python3
"""Canonical, MODEL-INDEPENDENT audit manifest for the cross-model comparison.

The path-based key used by ``audit_retention_v2`` embeds the nodes the MODEL
happened to sample, so two models with different neighbour samplers (the
official NeighborFinder vs the TGB NeighborSampler) almost never agree on a
path and the cross-arm join collapses.  This builder removes the model from the
question entirely:

  * the root->a1->a2->leaf chain is generated by a FIXED DETERMINISTIC rule from
    the raw UCI history, using only interactions strictly before the root time;
  * it depends on no model, no sampler, no checkpoint and no future label;
  * the cross-arm key is ``(canonical_root_event_id, hop, canonical_source_
    event_id)`` and never mentions the nodes a model sampled.

Root-event identity uses the RAW csv row, not any loader's internal edge id:

    canon_key = (raw_row_index, src, dst, timestamp, duplicate_ordinal)

so the TGB loader's ``idx`` and UCILinkDataset's ``edge_idxs`` cannot disagree.

Chain rule (deterministic, history-only)
----------------------------------------
    a1   = the most recent interaction partner of root strictly before t_root
    a2   = the most recent partner of a1 strictly before that interaction
    leaf = the most recent partner of a2 strictly before that interaction
Ties are broken by the smallest partner node id, then the smallest row index.

Targets (unchanged hop semantics):
    S^(1) = (Y_a1, Y_root)   S^(2) = (Y_a2, Y_a1)   S^(3) = (Y_leaf, Y_a2)
Each Y_v is "which presentation position holds the true candidate", with the
candidate pair = the node's first strict-future OUT edge vs one fixed negative
-- the same sampler convention the official extractor uses, itself model-free.

Usage:
    python scripts/build_canonical_manifest.py \
        --data-dir <.../uci> --data-name uci \
        --root-lo 29800 --root-hi 41800 \
        --out canonical_manifest.json
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

HOP_SRC = {1: ("a1", "root"), 2: ("a2", "a1"), 3: ("leaf", "a2")}


def _rng(node, t_root, salt):
    return np.random.RandomState((int(node) * 1000003 + int(t_root) + salt)
                                 % (2 ** 31))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", required=True)
    ap.add_argument("--data-name", default="uci")
    ap.add_argument("--root-lo", type=int, default=29800,
                    help="first raw csv row index to use as a root event")
    ap.add_argument("--root-hi", type=int, default=41800)
    ap.add_argument("--out", required=True)
    ap.add_argument("--max-roots", type=int, default=0, help="0 = no cap")
    args = ap.parse_args()

    import pandas as pd
    d = Path(args.data_dir)
    df = pd.read_csv(d / "ml_{}.csv".format(args.data_name))
    ts = df.ts.values.astype(np.float64)
    src = df.u.values.astype(np.int64)
    dst = df.i.values.astype(np.int64)
    n_edges = len(df)
    if not np.all(np.diff(ts) >= 0):
        raise SystemExit("the raw stream is not time-ordered; the canonical "
                         "rule assumes chronological rows")

    # duplicate ordinal over (src, dst, ts) so the key is unique even when the
    # raw file repeats an identical triple
    ordi = np.zeros(n_edges, dtype=np.int64)
    seen = {}
    order = np.lexsort((np.arange(n_edges), ts, dst, src))
    for j in order:
        k = (int(src[j]), int(dst[j]), float(ts[j]))
        ordi[j] = seen.get(k, 0)
        seen[k] = ordi[j] + 1

    # per-node history: (time, partner, row)
    hist = {}
    for j in range(n_edges):
        hist.setdefault(int(src[j]), []).append((float(ts[j]), int(dst[j]), j))
        hist.setdefault(int(dst[j]), []).append((float(ts[j]), int(src[j]), j))
    for v in hist:
        hist[v].sort(key=lambda x: (x[0], x[1], x[2]))

    ht = {v: np.array([x[0] for x in h], np.float64) for v, h in hist.items()}

    def prev_partner(node, t_before):
        """Most recent partner strictly before ``t_before`` (ties -> min id)."""
        h = hist.get(int(node))
        if not h:
            return None
        k = int(np.searchsorted(ht[int(node)], t_before, side="left"))
        if k == 0:
            return None
        best = None
        tt = h[k - 1][0]
        for i in range(k - 1, -1, -1):
            if h[i][0] != tt:
                break
            cand = h[i]
            key = (cand[1], cand[2])
            if best is None or key < (best[1], best[2]):
                best = cand
        return best

    # first strict-future OUT edge per node, for the candidate sampler
    out_rows = {}
    for j in range(n_edges):
        out_rows.setdefault(int(src[j]), []).append(j)
    out_t = {v: np.array([float(ts[j]) for j in r], np.float64)
             for v, r in out_rows.items()}

    def first_future_out(node, t_from):
        r = out_rows.get(int(node))
        if not r:
            return None
        k = int(np.searchsorted(out_t[int(node)], t_from, side="right"))
        return int(r[k]) if k < len(r) else None

    pool = np.unique(dst)

    def candidate(node, t_root):
        """Model-free candidate pair: first future OUT edge vs a fixed negative."""
        jf = first_future_out(node, t_root)
        if jf is None:
            return None
        dpos = int(dst[jf])
        g = _rng(node, t_root, 0)
        dneg = int(pool[g.randint(len(pool))])
        if dneg == dpos:
            for _ in range(64):
                d2 = int(pool[g.randint(len(pool))])
                if d2 != dpos:
                    dneg = d2
                    break
            else:
                return None
        pres = dpos if int(g.randint(2)) == 0 else dneg
        return {"pos": dpos, "neg": dneg, "presented": int(pres),
                "Y": 0 if pres == dpos else 1,          # canonical: position of truth
                "future_row": jf, "future_time": float(ts[jf])}

    lo = max(0, int(args.root_lo))
    hi = min(n_edges, int(args.root_hi))
    events = []
    n_skip = {"no_a1": 0, "no_a2": 0, "no_leaf": 0, "no_cand": 0}
    for j in range(lo, hi):
        r = int(src[j])
        t_root = float(ts[j])
        a1 = prev_partner(r, t_root)
        if a1 is None:
            n_skip["no_a1"] += 1
            continue
        a1_node, t_a1 = int(a1[1]), float(a1[0])
        a2 = prev_partner(a1_node, t_a1)
        if a2 is None:
            n_skip["no_a2"] += 1
            continue
        a2_node, t_a2 = int(a2[1]), float(a2[0])
        leaf = prev_partner(a2_node, t_a2)
        if leaf is None:
            n_skip["no_leaf"] += 1
            continue
        leaf_node, t_leaf = int(leaf[1]), float(leaf[0])
        nodes = {"root": r, "a1": a1_node, "a2": a2_node, "leaf": leaf_node}
        cands = {}
        bad = False
        for k, v in nodes.items():
            c = candidate(v, t_root)
            if c is None:
                bad = True
                break
            cands[k] = c
        if bad:
            n_skip["no_cand"] += 1
            continue
        events.append({
            "canon_key": [int(j), r, int(dst[j]), t_root, int(ordi[j])],
            "raw_row": int(j),
            "root_node": r, "t_root": t_root,
            "path": nodes,
            "path_times": {"a1": t_a1, "a2": t_a2, "leaf": t_leaf},
            # raw csv rows of the hop interactions: a1's edge to root, a2's edge
            # to a1, leaf's edge to a2 -- enough to rebuild the shared context
            "path_edge_rows": {"a1": int(a1[2]), "a2": int(a2[2]),
                               "leaf": int(leaf[2])},
            "cands": cands,
            "targets": {str(h): {"src": s, "parent": p,
                                 "Y_src": cands[s]["Y"],
                                 "Y_parent": cands[p]["Y"],
                                 "label": 2 * cands[s]["Y"] + cands[p]["Y"]}
                        for h, (s, p) in HOP_SRC.items()}})
        if args.max_roots and len(events) >= args.max_roots:
            break

    body = {"key_version": "canon_key=(raw_row,src,dst,ts,dup_ordinal)",
            "chain_rule": "most-recent-partner-before-root, ties=min(node,row)",
            "root_lo": lo, "root_hi": hi, "data_name": args.data_name,
            "n_events": len(events), "skipped": n_skip, "events": events}
    sha = hashlib.sha256(json.dumps(body, sort_keys=True, default=str)
                         .encode()).hexdigest()
    body["manifest_sha"] = sha
    with open(args.out, "w") as f:
        json.dump(body, f, default=str)
    print("[canonical] {} root events from rows [{}, {})  skipped={}  sha={}"
          .format(len(events), lo, hi, n_skip, sha[:16]), flush=True)
    print("wrote", args.out, flush=True)


if __name__ == "__main__":
    main()
